// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IMessageProtoBuf.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_IMessageProtoBuf_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_IMessageProtoBuf_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_IMessageProtoBuf_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_IMessageProtoBuf_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_IMessageProtoBuf_2eproto;
namespace ChatterCore {
namespace Protocols {
class IMessageProtoBuf;
class IMessageProtoBufDefaultTypeInternal;
extern IMessageProtoBufDefaultTypeInternal _IMessageProtoBuf_default_instance_;
}  // namespace Protocols
}  // namespace ChatterCore
PROTOBUF_NAMESPACE_OPEN
template<> ::ChatterCore::Protocols::IMessageProtoBuf* Arena::CreateMaybeMessage<::ChatterCore::Protocols::IMessageProtoBuf>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ChatterCore {
namespace Protocols {

enum IMessageProtoBuf_MessageTypeProtoBuf : int {
  IMessageProtoBuf_MessageTypeProtoBuf_CommandMessage = 0,
  IMessageProtoBuf_MessageTypeProtoBuf_ChatterMessage = 1,
  IMessageProtoBuf_MessageTypeProtoBuf_CommandResponseMessage = 2,
  IMessageProtoBuf_MessageTypeProtoBuf_IMessageProtoBuf_MessageTypeProtoBuf_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  IMessageProtoBuf_MessageTypeProtoBuf_IMessageProtoBuf_MessageTypeProtoBuf_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool IMessageProtoBuf_MessageTypeProtoBuf_IsValid(int value);
constexpr IMessageProtoBuf_MessageTypeProtoBuf IMessageProtoBuf_MessageTypeProtoBuf_MessageTypeProtoBuf_MIN = IMessageProtoBuf_MessageTypeProtoBuf_CommandMessage;
constexpr IMessageProtoBuf_MessageTypeProtoBuf IMessageProtoBuf_MessageTypeProtoBuf_MessageTypeProtoBuf_MAX = IMessageProtoBuf_MessageTypeProtoBuf_CommandResponseMessage;
constexpr int IMessageProtoBuf_MessageTypeProtoBuf_MessageTypeProtoBuf_ARRAYSIZE = IMessageProtoBuf_MessageTypeProtoBuf_MessageTypeProtoBuf_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* IMessageProtoBuf_MessageTypeProtoBuf_descriptor();
template<typename T>
inline const std::string& IMessageProtoBuf_MessageTypeProtoBuf_Name(T enum_t_value) {
  static_assert(::std::is_same<T, IMessageProtoBuf_MessageTypeProtoBuf>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function IMessageProtoBuf_MessageTypeProtoBuf_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    IMessageProtoBuf_MessageTypeProtoBuf_descriptor(), enum_t_value);
}
inline bool IMessageProtoBuf_MessageTypeProtoBuf_Parse(
    const std::string& name, IMessageProtoBuf_MessageTypeProtoBuf* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<IMessageProtoBuf_MessageTypeProtoBuf>(
    IMessageProtoBuf_MessageTypeProtoBuf_descriptor(), name, value);
}
// ===================================================================

class IMessageProtoBuf :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ChatterCore.Protocols.IMessageProtoBuf) */ {
 public:
  IMessageProtoBuf();
  virtual ~IMessageProtoBuf();

  IMessageProtoBuf(const IMessageProtoBuf& from);
  IMessageProtoBuf(IMessageProtoBuf&& from) noexcept
    : IMessageProtoBuf() {
    *this = ::std::move(from);
  }

  inline IMessageProtoBuf& operator=(const IMessageProtoBuf& from) {
    CopyFrom(from);
    return *this;
  }
  inline IMessageProtoBuf& operator=(IMessageProtoBuf&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const IMessageProtoBuf& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IMessageProtoBuf* internal_default_instance() {
    return reinterpret_cast<const IMessageProtoBuf*>(
               &_IMessageProtoBuf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(IMessageProtoBuf& a, IMessageProtoBuf& b) {
    a.Swap(&b);
  }
  inline void Swap(IMessageProtoBuf* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline IMessageProtoBuf* New() const final {
    return CreateMaybeMessage<IMessageProtoBuf>(nullptr);
  }

  IMessageProtoBuf* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<IMessageProtoBuf>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const IMessageProtoBuf& from);
  void MergeFrom(const IMessageProtoBuf& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IMessageProtoBuf* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ChatterCore.Protocols.IMessageProtoBuf";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_IMessageProtoBuf_2eproto);
    return ::descriptor_table_IMessageProtoBuf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef IMessageProtoBuf_MessageTypeProtoBuf MessageTypeProtoBuf;
  static constexpr MessageTypeProtoBuf CommandMessage =
    IMessageProtoBuf_MessageTypeProtoBuf_CommandMessage;
  static constexpr MessageTypeProtoBuf ChatterMessage =
    IMessageProtoBuf_MessageTypeProtoBuf_ChatterMessage;
  static constexpr MessageTypeProtoBuf CommandResponseMessage =
    IMessageProtoBuf_MessageTypeProtoBuf_CommandResponseMessage;
  static inline bool MessageTypeProtoBuf_IsValid(int value) {
    return IMessageProtoBuf_MessageTypeProtoBuf_IsValid(value);
  }
  static constexpr MessageTypeProtoBuf MessageTypeProtoBuf_MIN =
    IMessageProtoBuf_MessageTypeProtoBuf_MessageTypeProtoBuf_MIN;
  static constexpr MessageTypeProtoBuf MessageTypeProtoBuf_MAX =
    IMessageProtoBuf_MessageTypeProtoBuf_MessageTypeProtoBuf_MAX;
  static constexpr int MessageTypeProtoBuf_ARRAYSIZE =
    IMessageProtoBuf_MessageTypeProtoBuf_MessageTypeProtoBuf_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  MessageTypeProtoBuf_descriptor() {
    return IMessageProtoBuf_MessageTypeProtoBuf_descriptor();
  }
  template<typename T>
  static inline const std::string& MessageTypeProtoBuf_Name(T enum_t_value) {
    static_assert(::std::is_same<T, MessageTypeProtoBuf>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function MessageTypeProtoBuf_Name.");
    return IMessageProtoBuf_MessageTypeProtoBuf_Name(enum_t_value);
  }
  static inline bool MessageTypeProtoBuf_Parse(const std::string& name,
      MessageTypeProtoBuf* value) {
    return IMessageProtoBuf_MessageTypeProtoBuf_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSessionKeyFieldNumber = 2,
    kMessageTypeFieldNumber = 1,
  };
  // string sessionKey = 2;
  void clear_sessionkey();
  const std::string& sessionkey() const;
  void set_sessionkey(const std::string& value);
  void set_sessionkey(std::string&& value);
  void set_sessionkey(const char* value);
  void set_sessionkey(const char* value, size_t size);
  std::string* mutable_sessionkey();
  std::string* release_sessionkey();
  void set_allocated_sessionkey(std::string* sessionkey);
  private:
  const std::string& _internal_sessionkey() const;
  void _internal_set_sessionkey(const std::string& value);
  std::string* _internal_mutable_sessionkey();
  public:

  // .ChatterCore.Protocols.IMessageProtoBuf.MessageTypeProtoBuf messageType = 1;
  void clear_messagetype();
  ::ChatterCore::Protocols::IMessageProtoBuf_MessageTypeProtoBuf messagetype() const;
  void set_messagetype(::ChatterCore::Protocols::IMessageProtoBuf_MessageTypeProtoBuf value);
  private:
  ::ChatterCore::Protocols::IMessageProtoBuf_MessageTypeProtoBuf _internal_messagetype() const;
  void _internal_set_messagetype(::ChatterCore::Protocols::IMessageProtoBuf_MessageTypeProtoBuf value);
  public:

  // @@protoc_insertion_point(class_scope:ChatterCore.Protocols.IMessageProtoBuf)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sessionkey_;
  int messagetype_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_IMessageProtoBuf_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IMessageProtoBuf

// .ChatterCore.Protocols.IMessageProtoBuf.MessageTypeProtoBuf messageType = 1;
inline void IMessageProtoBuf::clear_messagetype() {
  messagetype_ = 0;
}
inline ::ChatterCore::Protocols::IMessageProtoBuf_MessageTypeProtoBuf IMessageProtoBuf::_internal_messagetype() const {
  return static_cast< ::ChatterCore::Protocols::IMessageProtoBuf_MessageTypeProtoBuf >(messagetype_);
}
inline ::ChatterCore::Protocols::IMessageProtoBuf_MessageTypeProtoBuf IMessageProtoBuf::messagetype() const {
  // @@protoc_insertion_point(field_get:ChatterCore.Protocols.IMessageProtoBuf.messageType)
  return _internal_messagetype();
}
inline void IMessageProtoBuf::_internal_set_messagetype(::ChatterCore::Protocols::IMessageProtoBuf_MessageTypeProtoBuf value) {
  
  messagetype_ = value;
}
inline void IMessageProtoBuf::set_messagetype(::ChatterCore::Protocols::IMessageProtoBuf_MessageTypeProtoBuf value) {
  _internal_set_messagetype(value);
  // @@protoc_insertion_point(field_set:ChatterCore.Protocols.IMessageProtoBuf.messageType)
}

// string sessionKey = 2;
inline void IMessageProtoBuf::clear_sessionkey() {
  sessionkey_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& IMessageProtoBuf::sessionkey() const {
  // @@protoc_insertion_point(field_get:ChatterCore.Protocols.IMessageProtoBuf.sessionKey)
  return _internal_sessionkey();
}
inline void IMessageProtoBuf::set_sessionkey(const std::string& value) {
  _internal_set_sessionkey(value);
  // @@protoc_insertion_point(field_set:ChatterCore.Protocols.IMessageProtoBuf.sessionKey)
}
inline std::string* IMessageProtoBuf::mutable_sessionkey() {
  // @@protoc_insertion_point(field_mutable:ChatterCore.Protocols.IMessageProtoBuf.sessionKey)
  return _internal_mutable_sessionkey();
}
inline const std::string& IMessageProtoBuf::_internal_sessionkey() const {
  return sessionkey_.GetNoArena();
}
inline void IMessageProtoBuf::_internal_set_sessionkey(const std::string& value) {
  
  sessionkey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void IMessageProtoBuf::set_sessionkey(std::string&& value) {
  
  sessionkey_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ChatterCore.Protocols.IMessageProtoBuf.sessionKey)
}
inline void IMessageProtoBuf::set_sessionkey(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  sessionkey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ChatterCore.Protocols.IMessageProtoBuf.sessionKey)
}
inline void IMessageProtoBuf::set_sessionkey(const char* value, size_t size) {
  
  sessionkey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ChatterCore.Protocols.IMessageProtoBuf.sessionKey)
}
inline std::string* IMessageProtoBuf::_internal_mutable_sessionkey() {
  
  return sessionkey_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* IMessageProtoBuf::release_sessionkey() {
  // @@protoc_insertion_point(field_release:ChatterCore.Protocols.IMessageProtoBuf.sessionKey)
  
  return sessionkey_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void IMessageProtoBuf::set_allocated_sessionkey(std::string* sessionkey) {
  if (sessionkey != nullptr) {
    
  } else {
    
  }
  sessionkey_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sessionkey);
  // @@protoc_insertion_point(field_set_allocated:ChatterCore.Protocols.IMessageProtoBuf.sessionKey)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocols
}  // namespace ChatterCore

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ChatterCore::Protocols::IMessageProtoBuf_MessageTypeProtoBuf> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ChatterCore::Protocols::IMessageProtoBuf_MessageTypeProtoBuf>() {
  return ::ChatterCore::Protocols::IMessageProtoBuf_MessageTypeProtoBuf_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_IMessageProtoBuf_2eproto
