// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegisterCommandResponseMessageProtoBuf.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_RegisterCommandResponseMessageProtoBuf_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_RegisterCommandResponseMessageProtoBuf_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_RegisterCommandResponseMessageProtoBuf_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_RegisterCommandResponseMessageProtoBuf_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_RegisterCommandResponseMessageProtoBuf_2eproto;
namespace ChatterBoxCore {
namespace Protocols {
class RegisterCommandResponseMessageProtoBuf;
class RegisterCommandResponseMessageProtoBufDefaultTypeInternal;
extern RegisterCommandResponseMessageProtoBufDefaultTypeInternal _RegisterCommandResponseMessageProtoBuf_default_instance_;
}  // namespace Protocols
}  // namespace ChatterBoxCore
PROTOBUF_NAMESPACE_OPEN
template<> ::ChatterBoxCore::Protocols::RegisterCommandResponseMessageProtoBuf* Arena::CreateMaybeMessage<::ChatterBoxCore::Protocols::RegisterCommandResponseMessageProtoBuf>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ChatterBoxCore {
namespace Protocols {

// ===================================================================

class RegisterCommandResponseMessageProtoBuf :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ChatterBoxCore.Protocols.RegisterCommandResponseMessageProtoBuf) */ {
 public:
  RegisterCommandResponseMessageProtoBuf();
  virtual ~RegisterCommandResponseMessageProtoBuf();

  RegisterCommandResponseMessageProtoBuf(const RegisterCommandResponseMessageProtoBuf& from);
  RegisterCommandResponseMessageProtoBuf(RegisterCommandResponseMessageProtoBuf&& from) noexcept
    : RegisterCommandResponseMessageProtoBuf() {
    *this = ::std::move(from);
  }

  inline RegisterCommandResponseMessageProtoBuf& operator=(const RegisterCommandResponseMessageProtoBuf& from) {
    CopyFrom(from);
    return *this;
  }
  inline RegisterCommandResponseMessageProtoBuf& operator=(RegisterCommandResponseMessageProtoBuf&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RegisterCommandResponseMessageProtoBuf& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegisterCommandResponseMessageProtoBuf* internal_default_instance() {
    return reinterpret_cast<const RegisterCommandResponseMessageProtoBuf*>(
               &_RegisterCommandResponseMessageProtoBuf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RegisterCommandResponseMessageProtoBuf& a, RegisterCommandResponseMessageProtoBuf& b) {
    a.Swap(&b);
  }
  inline void Swap(RegisterCommandResponseMessageProtoBuf* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RegisterCommandResponseMessageProtoBuf* New() const final {
    return CreateMaybeMessage<RegisterCommandResponseMessageProtoBuf>(nullptr);
  }

  RegisterCommandResponseMessageProtoBuf* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RegisterCommandResponseMessageProtoBuf>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RegisterCommandResponseMessageProtoBuf& from);
  void MergeFrom(const RegisterCommandResponseMessageProtoBuf& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegisterCommandResponseMessageProtoBuf* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ChatterBoxCore.Protocols.RegisterCommandResponseMessageProtoBuf";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_RegisterCommandResponseMessageProtoBuf_2eproto);
    return ::descriptor_table_RegisterCommandResponseMessageProtoBuf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRecoveryKeyFieldNumber = 6,
  };
  // string recoveryKey = 6;
  void clear_recoverykey();
  const std::string& recoverykey() const;
  void set_recoverykey(const std::string& value);
  void set_recoverykey(std::string&& value);
  void set_recoverykey(const char* value);
  void set_recoverykey(const char* value, size_t size);
  std::string* mutable_recoverykey();
  std::string* release_recoverykey();
  void set_allocated_recoverykey(std::string* recoverykey);
  private:
  const std::string& _internal_recoverykey() const;
  void _internal_set_recoverykey(const std::string& value);
  std::string* _internal_mutable_recoverykey();
  public:

  // @@protoc_insertion_point(class_scope:ChatterBoxCore.Protocols.RegisterCommandResponseMessageProtoBuf)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr recoverykey_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_RegisterCommandResponseMessageProtoBuf_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RegisterCommandResponseMessageProtoBuf

// string recoveryKey = 6;
inline void RegisterCommandResponseMessageProtoBuf::clear_recoverykey() {
  recoverykey_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& RegisterCommandResponseMessageProtoBuf::recoverykey() const {
  // @@protoc_insertion_point(field_get:ChatterBoxCore.Protocols.RegisterCommandResponseMessageProtoBuf.recoveryKey)
  return _internal_recoverykey();
}
inline void RegisterCommandResponseMessageProtoBuf::set_recoverykey(const std::string& value) {
  _internal_set_recoverykey(value);
  // @@protoc_insertion_point(field_set:ChatterBoxCore.Protocols.RegisterCommandResponseMessageProtoBuf.recoveryKey)
}
inline std::string* RegisterCommandResponseMessageProtoBuf::mutable_recoverykey() {
  // @@protoc_insertion_point(field_mutable:ChatterBoxCore.Protocols.RegisterCommandResponseMessageProtoBuf.recoveryKey)
  return _internal_mutable_recoverykey();
}
inline const std::string& RegisterCommandResponseMessageProtoBuf::_internal_recoverykey() const {
  return recoverykey_.GetNoArena();
}
inline void RegisterCommandResponseMessageProtoBuf::_internal_set_recoverykey(const std::string& value) {
  
  recoverykey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void RegisterCommandResponseMessageProtoBuf::set_recoverykey(std::string&& value) {
  
  recoverykey_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ChatterBoxCore.Protocols.RegisterCommandResponseMessageProtoBuf.recoveryKey)
}
inline void RegisterCommandResponseMessageProtoBuf::set_recoverykey(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  recoverykey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ChatterBoxCore.Protocols.RegisterCommandResponseMessageProtoBuf.recoveryKey)
}
inline void RegisterCommandResponseMessageProtoBuf::set_recoverykey(const char* value, size_t size) {
  
  recoverykey_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ChatterBoxCore.Protocols.RegisterCommandResponseMessageProtoBuf.recoveryKey)
}
inline std::string* RegisterCommandResponseMessageProtoBuf::_internal_mutable_recoverykey() {
  
  return recoverykey_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* RegisterCommandResponseMessageProtoBuf::release_recoverykey() {
  // @@protoc_insertion_point(field_release:ChatterBoxCore.Protocols.RegisterCommandResponseMessageProtoBuf.recoveryKey)
  
  return recoverykey_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void RegisterCommandResponseMessageProtoBuf::set_allocated_recoverykey(std::string* recoverykey) {
  if (recoverykey != nullptr) {
    
  } else {
    
  }
  recoverykey_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), recoverykey);
  // @@protoc_insertion_point(field_set_allocated:ChatterBoxCore.Protocols.RegisterCommandResponseMessageProtoBuf.recoveryKey)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocols
}  // namespace ChatterBoxCore

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_RegisterCommandResponseMessageProtoBuf_2eproto
